### ISSUE TITLE
Sepolicy issues

### ISSUE THREAD

**Issue by Mitomanu** [adeveloper79/android_device_lenovo_aio_otfp-n#6]
Hi,
I try build for Lenovo aio with your device, but some errors occured în sepolicy. Eg. platform_data, gps_device, and so on. How can this be fixed? I have observed this in mt6755 device tree either.

Thank you.

**Comment by adeveloper79** [comment]
Compile without sepolicy
The los15 branch was just a test branch (untested)

**Comment by Mitomanu** [comment]
Thank you
